development:
  adapter: postgresql
  encoding: utf8
  database: lunch_drunk_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: lunch_drunk_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: lunch_drunk_production
  pool: 5
  username:
  password:
